#ifndef __SOC_GLOBAL_DEFINE_H__
#define __SOC_GLOBAL_DEFINE_H__

#define USE_VOXELIZATION_WITH_INJECTION
#define USE_SHADOW_INVERTED_DEPTH
//#define USE_UI

#define LIGHT_CULLING_TILE_RES						16
#define LIGHT_CULLING_LIGHT_MAX_COUNT_IN_TILE 		256

#define INJECTION_TILE_RES 16
#define MIPMAPPING_TILE_RES_HALF 8

#endif