#ifndef __SOC_GLOBAL_DEFINE_H__
#define __SOC_GLOBAL_DEFINE_H__

#define USE_SHADOW_INVERTED_DEPTH
#define ENABLE_SKY_LIGHT
//#define USE_MOTION_BLUR
//#define USE_UI

#define LIGHT_CULLING_TILE_RES						16
#define LIGHT_CULLING_LIGHT_MAX_COUNT_IN_TILE 		256
#define INJECTION_TILE_RES							8
#define MIPMAPPING_TILE_RES_HALF					8
#define VOXEL_CONE_TRACING_TILE_RES					16
#define NUM_ENV_FILTER_SAMPLER						32	
#define MAXIMUM_LUMEN								25500
#define PRE_INTEGRATE_TILE_RES						16
#define BRDF_SAMPLES								64
#define POINT_LIGHT_BUFFER_MAX_NUM					2048
#define SPOT_LIGHT_BUFFER_MAX_NUM					2048
#define DIRECTIONAL_LIGHT_BUFFER_MAX_NUM			1024
#define LIGHT_BUFFER_OVERALL_UPDATE_RATE			0.5f

// Math
#define PI											3.141592654f
#define FLOAT_MAX									3.402823466e+38F

#endif